// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GamesService manages games from multiple sources
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

/**
 * CancelMetadataFetch cancels an active metadata fetch
 */
export function CancelMetadataFetch(instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(1664431675, instanceID);
}

/**
 * GetArtURL returns the HTTP URL for game art
 */
export function GetArtURL(instanceID: string, artType: string): $CancellablePromise<string> {
    return $Call.ByID(3242338708, instanceID, artType);
}

/**
 * GetDefaultFilterConfig returns the default filter configuration from config
 */
export function GetDefaultFilterConfig(): $CancellablePromise<models$0.GameFilter> {
    return $Call.ByID(160942279).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetEmulators returns all configured emulators
 */
export function GetEmulators(): $CancellablePromise<models$0.Emulator[]> {
    return $Call.ByID(484163394).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetEmulatorsForPlatform returns emulators available for a platform
 */
export function GetEmulatorsForPlatform(platform: string): $CancellablePromise<[models$0.Emulator[], models$0.EmulatorCore[]]> {
    return $Call.ByID(2492299158, platform).then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        $result[1] = $$createType4($result[1]);
        return $result;
    });
}

/**
 * GetGame returns a single game with all its instances
 */
export function GetGame(gameID: string): $CancellablePromise<[models$0.Game | null, models$0.GameInstance[]]> {
    return $Call.ByID(1663983004, gameID).then(($result: any) => {
        $result[0] = $$createType6($result[0]);
        $result[1] = $$createType8($result[1]);
        return $result;
    });
}

/**
 * GetGames returns games with optional filtering and sorting
 */
export function GetGames(filter: models$0.GameFilter | null, sortOpts: models$0.GameSort | null): $CancellablePromise<models$0.GameWithInstance[]> {
    return $Call.ByID(285073213, filter, sortOpts).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetSources returns list of available sources
 */
export function GetSources(): $CancellablePromise<string[]> {
    return $Call.ByID(1394397720).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Launch starts a game instance and monitors its process
 */
export function Launch(instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(75612669, instanceID);
}

/**
 * RefreshEmulators re-discovers available emulators
 */
export function RefreshEmulators(): $CancellablePromise<void> {
    return $Call.ByID(2111396207);
}

/**
 * RefreshGames rescans all sources and updates the database
 */
export function RefreshGames(): $CancellablePromise<void> {
    return $Call.ByID(3409273688);
}

/**
 * RefreshSource rescans a specific source
 */
export function RefreshSource(sourceName: string): $CancellablePromise<void> {
    return $Call.ByID(2194929836, sourceName);
}

/**
 * SetInstanceEmulator sets the emulator for a specific game instance
 */
export function SetInstanceEmulator(instanceID: string, emulatorID: string, coreID: string): $CancellablePromise<void> {
    return $Call.ByID(2146105962, instanceID, emulatorID, coreID);
}

/**
 * SetPlatformDefaultEmulator sets the default emulator for a platform
 */
export function SetPlatformDefaultEmulator(platform: string, emulatorID: string, coreID: string): $CancellablePromise<void> {
    return $Call.ByID(2560324241, platform, emulatorID, coreID);
}

/**
 * UpdateFilterConfig updates the filter configuration
 */
export function UpdateFilterConfig(steamExcludeTools: boolean): $CancellablePromise<void> {
    return $Call.ByID(3990429871, steamExcludeTools);
}

/**
 * UpdateInstanceMetadata updates custom metadata for an instance
 */
export function UpdateInstanceMetadata(instanceID: string, updates: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(4184085269, instanceID, updates);
}

// Private type creation functions
const $$createType0 = models$0.GameFilter.createFrom;
const $$createType1 = models$0.Emulator.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = models$0.EmulatorCore.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.Game.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = models$0.GameInstance.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.GameWithInstance.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
