// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * Emulator represents an emulator configuration
 */
export class Emulator {
    "id": string;
    "name": string;
    "displayName": string;
    "type": EmulatorType;
    "executablePath"?: string;
    "flatpakId"?: string;
    "commandTemplate": string;
    "defaultArgs"?: string;
    "supportedPlatforms": string[];
    "isAvailable": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Emulator instance. */
    constructor($$source: Partial<Emulator> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = EmulatorType.$zero;
        }
        if (!("commandTemplate" in $$source)) {
            this["commandTemplate"] = "";
        }
        if (!("supportedPlatforms" in $$source)) {
            this["supportedPlatforms"] = [];
        }
        if (!("isAvailable" in $$source)) {
            this["isAvailable"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Emulator instance from a string or object.
     */
    static createFrom($$source: any = {}): Emulator {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedPlatforms" in $$parsedSource) {
            $$parsedSource["supportedPlatforms"] = $$createField8_0($$parsedSource["supportedPlatforms"]);
        }
        return new Emulator($$parsedSource as Partial<Emulator>);
    }
}

/**
 * EmulatorCore represents a RetroArch core (Option B)
 */
export class EmulatorCore {
    "id": string;
    "emulatorId": string;
    "coreId": string;
    "displayName": string;
    "supportedPlatforms": string[];
    "isAvailable": boolean;

    /** Creates a new EmulatorCore instance. */
    constructor($$source: Partial<EmulatorCore> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("emulatorId" in $$source)) {
            this["emulatorId"] = "";
        }
        if (!("coreId" in $$source)) {
            this["coreId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("supportedPlatforms" in $$source)) {
            this["supportedPlatforms"] = [];
        }
        if (!("isAvailable" in $$source)) {
            this["isAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmulatorCore instance from a string or object.
     */
    static createFrom($$source: any = {}): EmulatorCore {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedPlatforms" in $$parsedSource) {
            $$parsedSource["supportedPlatforms"] = $$createField4_0($$parsedSource["supportedPlatforms"]);
        }
        return new EmulatorCore($$parsedSource as Partial<EmulatorCore>);
    }
}

/**
 * EmulatorType represents how the emulator is installed
 */
export enum EmulatorType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EmulatorTypeFlatpak = "flatpak",
    EmulatorTypeNative = "native",
    EmulatorTypeAppImage = "appimage",
};

/**
 * Game represents the abstract game entity
 */
export class Game {
    "id": string;
    "name": string;
    "description": string;
    "releaseDate"?: time$0.Time | null;
    "developer": string;
    "publisher": string;
    "genres": string[];
    "platforms": string[];
    "artUrls": { [_ in string]?: string };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Game instance. */
    constructor($$source: Partial<Game> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("developer" in $$source)) {
            this["developer"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("genres" in $$source)) {
            this["genres"] = [];
        }
        if (!("platforms" in $$source)) {
            this["platforms"] = [];
        }
        if (!("artUrls" in $$source)) {
            this["artUrls"] = {};
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Game instance from a string or object.
     */
    static createFrom($$source: any = {}): Game {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("genres" in $$parsedSource) {
            $$parsedSource["genres"] = $$createField6_0($$parsedSource["genres"]);
        }
        if ("platforms" in $$parsedSource) {
            $$parsedSource["platforms"] = $$createField7_0($$parsedSource["platforms"]);
        }
        if ("artUrls" in $$parsedSource) {
            $$parsedSource["artUrls"] = $$createField8_0($$parsedSource["artUrls"]);
        }
        return new Game($$parsedSource as Partial<Game>);
    }
}

/**
 * GameFilter represents filtering options for games
 */
export class GameFilter {
    "installedOnly": boolean;
    "source"?: string;
    "platform"?: string;
    "search"?: string;
    "genres"?: string[];

    /**
     * SourceFilters allows source-specific filtering
     * Key is source name (e.g., "steam"), value is map of filter options
     */
    "sourceFilters"?: { [_ in string]?: { [_ in string]?: any } };

    /** Creates a new GameFilter instance. */
    constructor($$source: Partial<GameFilter> = {}) {
        if (!("installedOnly" in $$source)) {
            this["installedOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): GameFilter {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("genres" in $$parsedSource) {
            $$parsedSource["genres"] = $$createField4_0($$parsedSource["genres"]);
        }
        if ("sourceFilters" in $$parsedSource) {
            $$parsedSource["sourceFilters"] = $$createField5_0($$parsedSource["sourceFilters"]);
        }
        return new GameFilter($$parsedSource as Partial<GameFilter>);
    }
}

/**
 * GameInstance represents a specific copy/installation of a game
 */
export class GameInstance {
    "id": string;
    "gameId": string;
    "source": string;
    "platform": string;
    "sourceId": string;
    "path"?: string;
    "filename"?: string;
    "fileSize"?: number;
    "fileHash"?: string;
    "installed": boolean;
    "installPath"?: string;
    "metadataStatus": MetadataStatus;
    "customMetadata": { [_ in string]?: any };
    "sourceData"?: { [_ in string]?: any };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new GameInstance instance. */
    constructor($$source: Partial<GameInstance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("metadataStatus" in $$source)) {
            this["metadataStatus"] = (new MetadataStatus());
        }
        if (!("customMetadata" in $$source)) {
            this["customMetadata"] = {};
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): GameInstance {
        const $$createField11_0 = $$createType4;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadataStatus" in $$parsedSource) {
            $$parsedSource["metadataStatus"] = $$createField11_0($$parsedSource["metadataStatus"]);
        }
        if ("customMetadata" in $$parsedSource) {
            $$parsedSource["customMetadata"] = $$createField12_0($$parsedSource["customMetadata"]);
        }
        if ("sourceData" in $$parsedSource) {
            $$parsedSource["sourceData"] = $$createField13_0($$parsedSource["sourceData"]);
        }
        return new GameInstance($$parsedSource as Partial<GameInstance>);
    }
}

/**
 * GameSort represents sorting options for games
 */
export class GameSort {
    /**
     * "name", "lastPlayed", "fileSize", "dateAdded"
     */
    "field": string;

    /**
     * "asc", "desc"
     */
    "order": string;

    /** Creates a new GameSort instance. */
    constructor($$source: Partial<GameSort> = {}) {
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameSort instance from a string or object.
     */
    static createFrom($$source: any = {}): GameSort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameSort($$parsedSource as Partial<GameSort>);
    }
}

/**
 * GameWithInstance combines game and instance data for UI
 */
export class GameWithInstance {
    "game": Game;
    "instance": GameInstance;

    /** Creates a new GameWithInstance instance. */
    constructor($$source: Partial<GameWithInstance> = {}) {
        if (!("game" in $$source)) {
            this["game"] = (new Game());
        }
        if (!("instance" in $$source)) {
            this["instance"] = (new GameInstance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameWithInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): GameWithInstance {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("game" in $$parsedSource) {
            $$parsedSource["game"] = $$createField0_0($$parsedSource["game"]);
        }
        if ("instance" in $$parsedSource) {
            $$parsedSource["instance"] = $$createField1_0($$parsedSource["instance"]);
        }
        return new GameWithInstance($$parsedSource as Partial<GameWithInstance>);
    }
}

/**
 * LaunchStatus represents the state of game launching/running
 */
export enum LaunchStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LaunchStatusLaunching = "launching",
    LaunchStatusRunning = "running",
    LaunchStatusStopped = "stopped",
    LaunchStatusFailed = "failed",
};

/**
 * LaunchStatusUpdate is sent via Wails events when game launch status changes
 */
export class LaunchStatusUpdate {
    "instanceId": string;
    "gameId": string;
    "status": LaunchStatus;
    "error"?: string;

    /** Creates a new LaunchStatusUpdate instance. */
    constructor($$source: Partial<LaunchStatusUpdate> = {}) {
        if (!("instanceId" in $$source)) {
            this["instanceId"] = "";
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = LaunchStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchStatusUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchStatusUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchStatusUpdate($$parsedSource as Partial<LaunchStatusUpdate>);
    }
}

/**
 * MetadataState represents the state of metadata fetching
 */
export enum MetadataState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MetadataStateIdle = "idle",
    MetadataStateFetching = "fetching",
    MetadataStateCompleted = "completed",
    MetadataStateError = "error",
    MetadataStateCancelled = "cancelled",
};

/**
 * MetadataStatus tracks async metadata fetching progress
 */
export class MetadataStatus {
    "state": MetadataState;
    "progress": number;
    "message"?: string;
    "error"?: string;
    "startedAt"?: time$0.Time | null;
    "completedAt"?: time$0.Time | null;
    "sourcesTried"?: string[];

    /** Creates a new MetadataStatus instance. */
    constructor($$source: Partial<MetadataStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = MetadataState.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataStatus {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourcesTried" in $$parsedSource) {
            $$parsedSource["sourcesTried"] = $$createField6_0($$parsedSource["sourcesTried"]);
        }
        return new MetadataStatus($$parsedSource as Partial<MetadataStatus>);
    }
}

/**
 * MetadataStatusUpdate is sent via Wails events
 */
export class MetadataStatusUpdate {
    "instanceId": string;
    "gameId": string;
    "status": MetadataStatus;

    /** Creates a new MetadataStatusUpdate instance. */
    constructor($$source: Partial<MetadataStatusUpdate> = {}) {
        if (!("instanceId" in $$source)) {
            this["instanceId"] = "";
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new MetadataStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataStatusUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataStatusUpdate {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField2_0($$parsedSource["status"]);
        }
        return new MetadataStatusUpdate($$parsedSource as Partial<MetadataStatusUpdate>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = MetadataStatus.createFrom;
const $$createType5 = Game.createFrom;
const $$createType6 = GameInstance.createFrom;
