//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../../rhythmerc/gentro-ui/services/games/models/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "launchStatusUpdate": $$createType0,
        "metadataStatusUpdate": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = models$0.LaunchStatusUpdate.createFrom;
const $$createType1 = models$0.MetadataStatusUpdate.createFrom;

configure();
