// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as models$0 from "../../../../rhythmerc/gentro-ui/services/games/models/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "launchStatusUpdate": models$0.LaunchStatusUpdate;
            "metadataStatusUpdate": models$0.MetadataStatusUpdate;
        }
    }
}
